# Generated by Django 4.2.5 on 2023-11-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banknote_authentication_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetmodels',
            name='serialized_model',
            field=models.TextField(),
        ),
    ]
